import Link from 'next/link';
import {getInvestigation, getSignal, useGolden} from '@/lib/api/client';
import {Badge} from '@/components/ui/badge';
import {Card, CardContent, CardHeader, CardTitle} from '@/components/ui/card';
import {Banner} from '@/components/common/Banner';
import {EmptyState} from '@/components/common/EmptyState';
import {ConfidenceBreakdown} from '@/components/signals/ConfidenceBreakdown';
import {StepList} from '@/components/investigation/StepList';
import {CompetitorTable} from '@/components/investigation/CompetitorTable';
import {RecommendationList} from '@/components/investigation/RecommendationList';
import {label, pct, score} from '@/lib/format';

const scopeTone = {
  brand_specific: 'bg-red-50 text-red-700',
  industry_wide: 'bg-amber-50 text-amber-700',
  inconclusive: 'bg-slate-100 text-slate-600',
  unknown: 'bg-slate-100 text-slate-600',
} as const;

export default async function Investigate({params}: {params: {id: string}}) {
  // `id` is a signal id (or the demo alias). Resolve its latest investigation.
  const signal = await getSignal(params.id);
  const investigationId = useGolden ? 'demo-investigation' : signal.latest_investigation?.id;
  if (!investigationId) {
    return (
      <main className="mx-auto max-w-3xl px-5 py-12">
        <EmptyState title="No investigation yet">
          This signal has not been investigated. Live investigations arrive in a later phase.
        </EmptyState>
      </main>
    );
  }
  const inv = await getInvestigation(investigationId);
  const report = inv.report;
  const evidenceHref = `/evidence/${inv.id}`;

  return (
    <main className="mx-auto max-w-6xl px-5 py-8">
      <Link href={`/dashboard/${inv.analysis_id}`} className="text-sm font-medium text-brand">
        ← Back to dashboard
      </Link>
      <div className="mt-5 flex flex-wrap items-center gap-3">
        <Badge>Investigation</Badge>
        {report && (
          <Badge className={scopeTone[report.scope.verdict]}>Scope: {label(report.scope.verdict)}</Badge>
        )}
      </div>
      <h1 className="mt-3 text-3xl font-bold capitalize text-navy">
        Why are {signal.aspect} complaints rising?
      </h1>
      <p className="mt-2 text-slate-600">
        Signal score {score(signal.score)} • {signal.sources_count} source types
        {report ? ` • confidence ${pct(report.confidence.score)}` : ''}
      </p>

      <Card className="mt-6">
        <CardContent className="pt-5">
          <StepList steps={inv.steps ?? []} />
        </CardContent>
      </Card>

      {inv.status === 'failed' && (
        <Banner tone="error" className="mt-6" title="Investigation failed">
          {inv.error ?? 'Unknown error.'}
        </Banner>
      )}
      {!report && inv.status !== 'failed' && (
        <Banner tone="info" className="mt-6">
          The investigation is still running.
        </Banner>
      )}

      {report && (
        <>
          {report.generated_by === 'fallback' && (
            <Banner tone="warning" className="mt-6" title="Generated by fallback">
              The language model was unavailable, so this report was assembled by deterministic rules from the
              collected evidence. Confidence is unaffected.
            </Banner>
          )}
          <div className="mt-6 grid gap-6 lg:grid-cols-[1.1fr_.9fr]">
            <Card>
              <CardHeader>
                <CardTitle>Summary</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="leading-7 text-slate-700">{report.summary}</p>
                <ul className="mt-5 space-y-3">
                  {(report.findings ?? []).map((f, i) => (
                    <li key={i} className="rounded-lg bg-brand-soft p-4">
                      <p className="text-sm leading-6 text-slate-700">{f.text}</p>
                      <div className="mt-2 text-xs">
                        <span className="text-slate-500">
                          {(f.evidence_ids ?? []).length} cited sources:{' '}
                        </span>
                        {(f.evidence_ids ?? []).map((id, n) => (
                          <Link key={id} href={`${evidenceHref}#evidence-${id}`} className="mr-2 font-semibold text-brand">
                            [{n + 1}]
                          </Link>
                        ))}
                      </div>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Confidence breakdown</CardTitle>
              </CardHeader>
              <CardContent>
                <ConfidenceBreakdown confidence={report.confidence} />
                <h3 className="mt-6 text-sm font-semibold text-navy">Source coverage</h3>
                <div className="mt-2 flex flex-wrap gap-2">
                  {(report.source_coverage ?? []).map((c) => (
                    <Badge key={c.source_type}>
                      {c.source_type} · {c.supporting}
                    </Badge>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>

          <div className="mt-6 grid gap-6 lg:grid-cols-2">
            <Card>
              <CardHeader>
                <CardTitle>Scope: our problem or the market&apos;s?</CardTitle>
              </CardHeader>
              <CardContent>
                <Badge className={scopeTone[report.scope.verdict]}>{label(report.scope.verdict)}</Badge>
                <p className="mt-3 text-sm leading-6 text-slate-600">{report.scope.explanation}</p>
                {report.search_interest && (
                  <p className="mt-3 text-xs text-slate-500">
                    Search interest for “{report.search_interest.keyword}”:{' '}
                    {report.search_interest.change_pct == null ? 'n/a' : `${report.search_interest.change_pct}%`}
                  </p>
                )}
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Recommendations</CardTitle>
              </CardHeader>
              <CardContent>
                <RecommendationList items={report.recommendations ?? []} evidenceBase={evidenceHref} />
              </CardContent>
            </Card>
          </div>

          {report.competitor_comparison && (
            <Card className="mt-6">
              <CardHeader>
                <CardTitle>Competitor comparison</CardTitle>
              </CardHeader>
              <CardContent>
                <CompetitorTable comparison={report.competitor_comparison} />
              </CardContent>
            </Card>
          )}
          <p className="mt-6 text-xs text-slate-500">{report.disclaimer}</p>
        </>
      )}

      <Link href={evidenceHref} className="mt-6 inline-flex font-semibold text-brand">
        Explore evidence →
      </Link>
    </main>
  );
}
